# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-04 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='profesor',
            new_name='docente',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='identificacion',
        ),
        migrations.AddField(
            model_name='materia',
            name='id_docente',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
